# Site settings
title: Juchang Kim
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Juchang Kim
user_description: Studying in computer information and science in AUT. Interested in software development, project management, database, programming etc.
user_title: Student in AUT
email: brad193026@gmail.com
# twitter_username: lorem_ipsum
instagram_username: 
facebook_username: mauricio.urraco
linkedin : www.linkedin.com/in/juchang-kim 
github_username:  Juchang Kim
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

